# Generated by Django 3.0.5 on 2020-09-09 22:05

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emp',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(default='none', max_length=100)),
                ('email', models.EmailField(default='none', max_length=254)),
                ('username', models.CharField(default='undefined', max_length=100)),
                ('password', models.CharField(default='none', max_length=32)),
                ('role', models.CharField(default='Employee', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(default=datetime.datetime(2100, 8, 31, 1, 32, 9, 168460))),
            ],
        ),
    ]
