# Generated by Django 3.0.5 on 2020-07-19 17:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_emp__id'),
    ]

    operations = [
        migrations.AddField(
            model_name='emp',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
