# Generated by Django 3.0.5 on 2020-09-10 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200910_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp',
            name='id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
