# Generated by Django 3.0.5 on 2020-07-24 00:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_emp_created_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emp',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='emp',
            name='password',
        ),
        migrations.RemoveField(
            model_name='emp',
            name='role',
        ),
        migrations.RemoveField(
            model_name='emp',
            name='username',
        ),
        migrations.AddField(
            model_name='emp',
            name='email',
            field=models.EmailField(default='none', max_length=100),
        ),
        migrations.CreateModel(
            name='HR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=32)),
                ('role', models.CharField(max_length=10)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emp_name', to='api.Emp')),
            ],
        ),
    ]
