# Generated by Django 3.0.5 on 2020-07-24 01:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_hr_emp_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HR',
        ),
        migrations.AddField(
            model_name='emp',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 24, 7, 3, 53, 134032)),
        ),
        migrations.AddField(
            model_name='emp',
            name='password',
            field=models.CharField(default='null', max_length=32),
        ),
        migrations.AddField(
            model_name='emp',
            name='role',
            field=models.CharField(default='Employee', max_length=10),
        ),
        migrations.AddField(
            model_name='emp',
            name='username',
            field=models.CharField(default='undefined', max_length=100),
        ),
        migrations.AlterField(
            model_name='emp',
            name='email',
            field=models.EmailField(default='none', max_length=254),
        ),
        migrations.AlterField(
            model_name='emp',
            name='name',
            field=models.CharField(default='none', max_length=100),
        ),
    ]
