# Generated by Django 3.0.5 on 2020-07-24 01:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200724_0703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 24, 7, 5, 29, 955121)),
        ),
        migrations.AlterField(
            model_name='emp',
            name='password',
            field=models.CharField(default='none', max_length=32),
        ),
    ]
