# Generated by Django 3.0.5 on 2020-07-24 01:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20200724_0705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 24, 7, 24, 44, 843489)),
        ),
    ]
