# Generated by Django 3.0.5 on 2020-09-09 23:01

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20200724_0724'),
    ]

    operations = [
        migrations.AddField(
            model_name='emp',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2100, 8, 31, 1, 32, 9, 168460)),
        ),
        migrations.AddField(
            model_name='emp',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='emp',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='emp',
            name='id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='emp',
            name='role',
            field=models.CharField(default='Employee', max_length=100),
        ),
    ]
